export const USER_ACTION_TYPES = {
  SET_USER: "SET_USER",
};

export const ALERTS_ACTION_TYPES = {
  SET_ALERTS: "SET_ALERTS",
};

export const SHARED_ACTION_TYPES = {
  RESET_STORE: "RESET_STORE",
};

export const DRESS_CHOICE_ACTIONS = {
  SET_ALL_GARMENTS: "SET_ALL_GARMENTS",
  SET_GARMENT_SELECTION: "SET_GARMENT_SELECTION",
  SET_WAYPOINTS: "SET_WAYPOINTS",
  SET_WAYPOINTS_DATA: "SET_WAYPOINTS_DATA",
  SET_LOCATION_DATA_PANEL_VISIBILITY: "SET_LOCATION_DATA_PANEL_VISIBILITY",
};
