export const USER_ACTION_TYPES = {
  SET_USER: "SET_USER",
  SET_USER_LOCATIONS: "SET_USER_LOCATIONS",
};

export const ALERTS_ACTION_TYPES = {
  SET_ALERTS: "SET_ALERTS",
};

export const SHARED_ACTION_TYPES = {
  RESET_STORE: "RESET_STORE",
  LOCATION_CHANGE: "@@router/LOCATION_CHANGE",
};

export const DRESS_CHOICE_ACTIONS = {
  SET_ALL_GARMENTS: "SET_ALL_GARMENTS",
  SET_GARMENT_SELECTION: "SET_GARMENT_SELECTION",
  SET_WAYPOINTS: "SET_WAYPOINTS",
  SET_WAYPOINTS_DATA: "SET_WAYPOINTS_DATA",
  SET_ASSESSMENT: "SET_ASSESSMENT",
  SET_LOCATION_DATA_PANEL_VISIBILITY: "SET_LOCATION_DATA_PANEL_VISIBILITY",
};

export const STATISTICS_ACTIONS = {
  SET_WAYPOINT: "SET_STATISTICS_WAYPOINT",
  SET_DATA: "SET_STATISTICS_DATA",
};
